using System.Diagnostics.CodeAnalysis;
using Sushi.Diagnostics;
using Sushi.Tokenization;

namespace Sushi.Parsing.Nodes;

/// <summary>
/// Represents a single node, the smallest unit of code, generated by the parser.
/// </summary>
public abstract class SyntaxNode
{

    /// <summary>
    /// The <see cref="CompilerMessage"/> objects generated by the parser.
    /// </summary>
    public List<CompilerMessage> Messages { get; set; } = [];

    /// <summary>
    /// Gets the messages of this node and all child nodes.
    /// </summary>
    /// <returns></returns>
    public abstract List<CompilerMessage> GetMessages();

    /// <summary>
    /// Gets the starting <see cref="Token"/> for this node.
    /// </summary>
    /// <returns>
    /// An awaitable <see cref="Task"/>.
    /// </returns>
    public abstract Token? GetStartToken();

    /// <summary>
    /// Gets the ending <see cref="Token"/> for this node.
    /// </summary>
    /// <returns>
    /// An awaitable <see cref="Task"/>.
    /// </returns>
    public abstract Token? GetEndToken();
}