using Sushi.Diagnostics;
using Sushi.Tokenization;

namespace Sushi.Parsing.Nodes;

/// <summary>
/// Represents a single node, the smallest unit of code, generated by the parser.
/// </summary>
public abstract class SyntaxNode
{
    /// <summary>
    /// Gets the messages of this node and all child nodes.
    /// </summary>
    /// <returns>
    /// An <see cref="IAsyncEnumerable{T}"/> of <see cref="CompilerMessage"/> objects.
    /// </returns>
    public abstract IAsyncEnumerable<CompilerMessage> GetMessages();

    /// <summary>
    /// Gets the <see cref="Token"/> objects that make up this node.
    /// </summary>
    /// <returns>
    /// An <see cref="IAsyncEnumerable{T}"/> of <see cref="Token"/> objects.
    /// </returns>
    public abstract IAsyncEnumerable<Token> GetTokens();
}