using System.Diagnostics.CodeAnalysis;
using Sushi.Compilation;
using Sushi.Tokenization;
using Sushi.Verification;

namespace Sushi.Parsing.Nodes;

/// <summary>
/// Represents a single node, the smallest unit of code, generated by the parser.
/// </summary>
public abstract class SyntaxNode : ICompilerNode
{
    /// <summary>
    /// Called during the compile step to translate this node into intermediate source code.
    /// </summary>
    /// <param name="compiler">
    /// The <see cref="Compiler"/> object used to write.
    /// </param>
    /// <returns>
    /// An awaitable <see cref="Task"/>.
    /// </returns>
    public virtual Task Compile([NotNull] Compiler compiler) => Task.CompletedTask;

    /// <summary>
    /// Called during the compile step to translate this node into intermediate header code.
    /// </summary>
    /// <param name="compiler">
    /// The <see cref="Compiler"/> object used to write.
    /// </param>
    /// <returns>
    /// An awaitable <see cref="Task"/>.
    /// </returns>
    public virtual Task CompileHeader([NotNull] Compiler compiler) => Task.CompletedTask;

    /// <summary>
    /// Gets the starting <see cref="Token"/> for this node.
    /// </summary>
    /// <returns>
    /// An awaitable <see cref="Task"/>.
    /// </returns>
    public abstract Token? GetStartToken();

    /// <summary>
    /// Verifies that the node is valid.
    /// </summary>
    /// <param name="context">
    /// The verification context used to track messages.
    /// </param>
    /// <returns>
    /// An awaitable <see cref="Task"/>.
    /// </returns>
    public abstract Task Verify(VerificationContext context);
}
