using SushiCompiler.Parsing;
using SushiCompiler.Parsing.Nodes;
using System.Text;

namespace SushiCompiler.Compiling.L2.ILGenerators;

internal class FileILGenerator : ILGenerator
{
    internal override async Task<string> GenerateIL(SyntaxNode node, List<ILGenerator> ilGenerators)
    {
        if (node is not FileNode fileNode)
        {
            return string.Empty;
        }

        StringBuilder sb = new();

        sb.AppendLine("# Generated by SushiCompiler");

        foreach (var childNode in fileNode.Children)
        {
            if (childNode.ILGenerator is null)
            {
                continue;
            }

            ILGenerator? existing = ilGenerators.FirstOrDefault(x => x.GetType() == childNode.ILGenerator) ?? throw new InvalidOperationException("No generator found for node");

            sb.Append(await existing.GenerateIL(childNode, ilGenerators));
        }

        return sb.ToString();
    }
}
