namespace Sushi.Lexing.Tokenization;

/// <summary>
/// Represents a single token, the smallest unit of code, generated by the lexer.
/// </summary>
public sealed class Token
{
    /// <summary>
    /// The type of the <see cref="Token"/>.
    /// </summary>
    public required TokenType Type { get; set; }

    /// <summary>
    /// The value of the <see cref="Token"/>.
    /// </summary>
    public required string Value { get; set; }

    /// <summary>
    /// The line the <see cref="Token"/> appears in.
    /// </summary>
    public required int LineNumber { get; set; }

    /// <summary>
    /// The position of the <see cref="Token"/> in the line it appears in.
    /// </summary>
    public required int LinePosition { get; set; }

    /// <summary>
    /// The line that this <see cref="Token"/> appears on as a string.
    /// </summary>
    public string CurrentLine { get; set; } = string.Empty;
}
