using System.Diagnostics.CodeAnalysis;
using Sushi.Compilation;
using Sushi.Tokenization;

namespace Sushi.Parsing.Nodes;

/// <summary>
/// Represents a single node, the smallest unit of code, generated by the parser.
/// </summary>
public abstract class SyntaxNode
{
    /// <summary>
    /// Called during the compile step to translate this node into intermediate source code.
    /// </summary>
    /// <param name="compiler">
    /// The <see cref="CompilerVisitor"/> object used to write.
    /// </param>
    /// <returns>
    /// An awaitable <see cref="Task"/>.
    /// </returns>
    public virtual Task Compile([NotNull] CompilerVisitor compiler) => Task.CompletedTask;

    /// <summary>
    /// Called during the compile step to translate this node into intermediate header code.
    /// </summary>
    /// <param name="compiler">
    /// The <see cref="CompilerVisitor"/> object used to write.
    /// </param>
    /// <returns>
    /// An awaitable <see cref="Task"/>.
    /// </returns>
    public virtual Task CompileHeader([NotNull] CompilerVisitor compiler) => Task.CompletedTask;
}