using System.Diagnostics.CodeAnalysis;
using System.Text;
using Sushi.Parsing.Nodes;
using Sushi.Precompilation;

namespace Sushi.Compilation;

/// <summary>
/// Compiles an <see cref="AbstractSyntaxTree"/> into another language.
/// </summary>
public abstract class CompilerVisitor : ASTVisitor
{
    /// <summary>
    /// Prepended to the beginning of every file to indicate that it is generated by the compiler
    /// and should not be modified.
    /// </summary>
    private const string GeneratedFileComment = "Compiler-generated file, do not modify directly as it will be overwritten";

    /// <summary>
    /// The list of compiled files to be returned by the compile method.
    /// </summary>
    protected List<CompiledFile> CompiledFiles { get; } = [];

    /// <summary>
    /// Writes the generated comment to the file.
    /// </summary>
    /// <param name="generatedComment">
    /// The comment.
    /// </param>
    /// <returns>
    /// An awaitable <see cref="Task"/> that returns the comment string.
    /// </returns>
    protected abstract Task<string> WriteComment(string generatedComment);

    /// <summary>
    /// The indentation level used to format the generated file.
    /// </summary>
    private int indentLevel;

    /// <summary>
    /// Indicates whether the <see cref="StringBuilder"/> is currently on the first write of the line,
    /// so that it knows whether or not to include the indent in the next append.
    /// </summary>
    private bool firstOfLine = true;

    /// <summary>
    /// The current file being compiled.
    /// </summary>
    private CompiledFile currentFile = null!;

    /// <summary>
    /// The <see cref="StringBuilder"/> used to build the file contents.
    /// </summary>
    private readonly StringBuilder sb = new();

    /// <summary>
    /// The intermediate folder that will contain the generated files.
    /// </summary>
    private string intermediateFolder = string.Empty;

    /// <summary>
    /// The <see cref="ReferenceResolver"/> used for resolving references and expanding scoped names to their full names.
    /// </summary>
    protected ReferenceResolver Reference { get; private set; } = null!;

    /// <summary>
    /// Sets the intermediate folder path.
    /// </summary>
    /// <returns>
    /// An awaitable <see cref="Task"/>.
    /// </returns>
    private async Task SetIntermediateFolder()
    {
        DirectoryInfo intermediate = new(Path.Combine(AppMeta.Options.ProjectPath, "intermediate"));

        if (Directory.Exists(intermediate.FullName))
        {
            Directory.Delete(intermediate.FullName, true);
        }

        Directory.CreateDirectory(intermediate.FullName);

        this.intermediateFolder = intermediate.FullName;
    }

    /// <summary>
    /// Converts a source file path to an intermediate file path.
    /// </summary>
    /// <param name="sourcePath">
    /// The source path.
    /// </param>
    /// <param name="newExtension">
    /// The new extension of the file.
    /// </param>
    /// <returns>
    /// An awaitable <see cref="Task"/> that returns the source path.
    /// </returns>
    private async Task<string> ConvertSourcePathToIntermediatePath(string sourcePath, string newExtension)
    {
        string absoluteFilePath = Path.GetFullPath(sourcePath);

        Uri fullUri = new(absoluteFilePath);

        string projectPath = $"{AppMeta.Options.ProjectPath.TrimEnd('/', '\\')}{Path.DirectorySeparatorChar}";

        Uri baseUri = new(projectPath);

        Uri relativeUri = baseUri.MakeRelativeUri(fullUri);

        string relativeFilePath = Uri.UnescapeDataString(relativeUri.ToString()).Replace('/', Path.DirectorySeparatorChar);

        string newFilePath = Path.Combine(this.intermediateFolder, relativeFilePath);

        string fileDirectory = Path.GetDirectoryName(newFilePath) ?? string.Empty;

        if (!Directory.Exists(fileDirectory))
        {
            Directory.CreateDirectory(fileDirectory);
        }

        return Path.ChangeExtension(newFilePath, newExtension);
    }

    /// <summary>
    /// Compiles an <see cref="AbstractSyntaxTree"/> into a <see cref="List{T}"/> of <see cref="CompiledFile"/> objects.
    /// </summary>
    /// <param name="tree">
    /// The <see cref="AbstractSyntaxTree"/> to compile.
    /// </param>
    /// <param name="reference">
    /// The <see cref="ReferenceResolver"/> used to resolve references and expand scoped names into full names.
    /// </param>
    /// <returns>
    /// An awaitable <see cref="Task"/> that returns a <see cref="List{T}"/> of <see cref="CompiledFile"/> objects.
    /// </returns>
    public async Task<List<CompiledFile>> Compile([NotNull] AbstractSyntaxTree tree, [NotNull] ReferenceResolver reference)
    {
        this.Reference = reference;

        await this.SetIntermediateFolder();

        await this.Visit(tree);

        return this.CompiledFiles;
    }

    /// <summary>
    /// Starts a new file to be written.
    /// </summary>
    /// <param name="filePath">
    /// The location to write the file in.
    /// </param>
    /// <returns>
    /// An awaitable <see cref="Task"/>.
    /// </returns>
    protected async Task StartFile(string filePath)
    {
        this.sb.Clear();
        this.indentLevel = 0;
        CompiledFile compiledFile = new()
        {
            FilePath = filePath,
        };
        this.currentFile = compiledFile;
    }

    /// <summary>
    /// Closes out the file currently being written and cleans it up.
    /// </summary>
    /// <returns>
    /// An awaitable <see cref="Task"/>.
    /// </returns>
    protected async Task EndFile()
    {
        string contents = this.sb.ToString().Trim();

        // If the file contents are empty, don't even create one
        if (string.IsNullOrWhiteSpace(contents))
        {
            return;
        }

        this.CompiledFiles.Add(this.currentFile);

        StringBuilder contentsSB = new();

        contentsSB.AppendLine(await this.WriteComment(GeneratedFileComment));
        contentsSB.AppendLine(contents);
        this.currentFile.Content = contentsSB.ToString().Trim();
    }

    /// <summary>
    /// Creates a pad string that can be used to prepend the next line for indentation.
    /// </summary>
    /// <returns>
    /// An awaitable <see cref="Task"/> that returns the string padding.
    /// </returns>
    private Task<string> Pad()
    {
        StringBuilder pad = new();

        for (int i = 0; i < this.indentLevel * 4; i++)
        {
            pad.Append(' ');
        }

        return Task.FromResult(pad.ToString());
    }

    /// <summary>
    /// Writes a line to the current file.
    /// </summary>
    /// <param name="line">
    /// The line to write.
    /// </param>
    /// <returns>
    /// An awaitable <see cref="Task"/>.
    /// </returns>
    public Task WriteLine([NotNull] string line)
    {
        this.sb.AppendLine($"{this.Pad()}{line}");
        this.firstOfLine = true;
        return Task.CompletedTask;
    }

    /// <summary>
    /// Appends some text to the current line of the current file.
    /// </summary>
    /// <param name="text">
    /// The text to append. If it is the first text of the line, padding will be prepended.
    /// </param>
    /// <returns>
    /// An awaitable <see cref="Task"/>.
    /// </returns>
    public Task Write([NotNull] string text)
    {
        if (this.firstOfLine)
        {
            this.sb.Append($"{this.Pad()}{text}");
        }
        else
        {
            this.sb.Append(text);
        }

        this.firstOfLine = false;

        return Task.CompletedTask;
    }

    /// <summary>
    /// Ends the current line. Used to reset the head of the string builder
    /// and ensure the next text gets indented.
    /// </summary>
    /// <returns>
    /// An awaitable <see cref="Task"/>.
    /// </returns>
    public Task EndLine()
    {
        this.sb.AppendLine();
        this.firstOfLine = true;
        return Task.CompletedTask;
    }

    /// <summary>
    /// Increases the current indentation level.
    /// </summary>
    /// <returns>
    /// An awaitable <see cref="Task"/>.
    /// </returns>
    public Task Indent()
    {
        this.indentLevel++;
        return Task.CompletedTask;
    }

    /// <summary>
    /// Decreases the current indentation level.
    /// </summary>
    /// <returns>
    /// An awaitable <see cref="Task"/>.
    /// </returns>
    public Task Dedent()
    {
        this.indentLevel--;
        return Task.CompletedTask;
    }

}
