using System.Diagnostics.CodeAnalysis;
using Sushi.Diagnostics;
using Sushi.Parsing.Nodes;

namespace Sushi.Precompilation;

/// <summary>
/// Visits each node of the <see cref="AbstractSyntaxTree"/> and checks it for correctness.
/// If it finds errors or warnings, it generates them and adds them to the list.
/// </summary>
public sealed class VerificationVisitor : ASTVisitor
{
    /// <summary>
    /// The list of compiler messages generated by the visitor.
    /// </summary>
    private readonly List<CompilerMessage> messages = [];

    /// <summary>
    /// Verifies an <see cref="AbstractSyntaxTree"/> for errors and warnings.
    /// </summary>
    /// <param name="tree">
    /// The <see cref="AbstractSyntaxTree"/> to verify.
    /// </param>
    /// <returns>
    /// An awaitable <see cref="Task"/>.
    /// </returns>
    public async Task Verify([NotNull] AbstractSyntaxTree tree)
    {
        await this.Visit(tree);
        tree.Messages.AddRange(this.messages);
    }
}
