using System.Diagnostics.CodeAnalysis;
using Sushi.Diagnostics;
using Sushi.Diagnostics.Errors;
using Sushi.Parsing.Nodes;

namespace Sushi.Precompilation;

/// <summary>
/// Visits each node of the <see cref="AbstractSyntaxTree"/> and checks it for correctness.
/// If it finds errors or warnings, it generates them and adds them to the list.
/// </summary>
public sealed class VerificationVisitor : ASTVisitor
{

    /// <summary>
    /// The list of compiler messages generated by the visitor.
    /// </summary>
    private readonly List<CompilerMessage> messages = [];

    /// <summary>
    /// The current class node.
    /// </summary>
    private ClassNode? currentClass;

    /// <summary>
    /// The current creator declaration node.
    /// </summary>
    private CreatorDeclarationNode? currentCreator;

    /// <summary>
    /// Verifies an <see cref="AbstractSyntaxTree"/> for errors and warnings.
    /// </summary>
    /// <param name="tree">
    /// The <see cref="AbstractSyntaxTree"/> to verify.
    /// </param>
    /// <returns>
    /// An awaitable <see cref="Task"/>.
    /// </returns>
    public async Task Verify([NotNull] AbstractSyntaxTree tree)
    {
        await this.Visit(tree);
        tree.Messages.AddRange(this.messages);
    }

    /// <inheritdoc />
    protected override async Task VisitTree([NotNull] AbstractSyntaxTree tree)
    {
        foreach (FileNode child in tree.Children)
        {
            await this.Visit(child);
        }
    }

    /// <inheritdoc />
    protected override async Task VisitFile([NotNull] FileNode file)
    {
        foreach (StatementNode statement in file.Statements)
        {
            await this.Visit(statement);
        }
    }

    /// <inheritdoc />
    protected override async Task VisitClass([NotNull] ClassNode classNode)
    {
        this.currentClass = classNode;
        if (classNode.TypeName is not null)
        {
            await this.Visit(classNode.TypeName);
        }

        foreach (StatementNode member in classNode.Members)
        {
            await this.Visit(member);
        }

        this.currentClass = null;
    }

    /// <inheritdoc />
    protected override async Task VisitAssignment([NotNull] AssignmentNode assignment)
    {
        //this.currentAssignment = assignment;

        if (assignment.Identifier is not null)
        {
            await this.Visit(assignment.Identifier);
        }

        if (assignment.Right is not null)
        {
            await this.Visit(assignment.Right);
        }

        //this.currentAssignment = null;
    }

    /// <inheritdoc/>
    protected override async Task VisitDestroyerDeclaration([NotNull] DestroyerDeclarationNode destroyer)
    {
        List<MemberDeclarationNode> members = [.. this.currentClass!.Members.OfType<MemberDeclarationNode>()];

        if (destroyer.Body is not null)
        {
            foreach (StatementNode statement in destroyer.Body.Statements)
            {
                if (statement is DestroyNode destroy && destroy.Object is not null)
                {
                    MemberDeclarationNode member = members.First(x => x.Identifier!.Name == destroy.Object.Name);
                    members.Remove(member);
                }

                await this.Visit(statement);
            }

            if (members.Count > 0)
            {
                this.messages.Add(new UndestroyedMemberError(destroyer.GetStartToken(), members));
            }
        }
    }
}
